# This is a basic workflow to help you get started with Actions

name: CodeQL and QA

# Controls when the workflow will run
on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Perform QA
        run: make qa

      - name: Prepare codeql
        run: echo "CODEQL_PYTHON=$(which python)" >> $GITHUB_ENV

      - uses: github/codeql-action/init@v1
        with:
          db-location: '${{ github.workspace }}/codeql_dbs'
          languages: python
          setup-python-dependencies: false
