dist: xenial   # required for Python >= 3.7
language: python

python:
- "3.6"
# - "3.7"
# - "3.4"
# - "3.8-dev"

# matrix:
#   allow_failures:
#     - python: "3.4"
#     - python: "3.8-dev"

jobs:
  include:
    - stage: test
      script: make
    - stage: build & push
      script: make pull_image image push_image
      if: branch = master
